#!/usr/bin/env perl

use warnings;
use strict;

my $rem = $#ARGV ? shift(@ARGV) : 'upstream';
my $arg = $ARGV[0] || '.';

chomp(my $url = `git remote -v`);
$url = (grep {m/\(fetch\)/} grep {m/^$rem\s/} split(/\n/, $url))[0];
$url or die "oops";

$url =~ s/\s+\(fetch\)//;
$url =~ s/^.*\s+//;
$url =~ s/\.git$//;
$url =~ s{git@([^:]+):}{https://$1/};
$url =~ s{/*$}{/};

if(-d $arg) {
  $url .= 'tree/master/' . $arg unless $arg eq '.';
}
elsif(-f $arg) {
  $url .= 'blob/master/' . $arg;
}
else {
  $url .= 'commit/' . $arg;
}

print $url, "\n";


# vim:ts=2:sw=2:et:sta
